name: Doxygen Action
on: [push]

jobs:
  doxygen:
    runs-on: ${{ matrix. os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: sudo ./ci/install_dependencies.sh

    - name: Doxygen Build
      run: |
        mkdir build && cd build
        cmake ..
        make doxygen
        cd ..

    - name: Doxygen Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/html
